version: 2.1
executors:
  default:
    working_directory: ~/nextjs-typescript-firebase
    docker:
      - image: node:12

commands:
  restore_npm:
    steps:
      - restore_cache:
          name: Restore npm dependencies
          key:
            - v1-dependencies-{{ checksum "package.json" }
            - v1-dependencies- 

  save_npm:
    steps:
      - save_cache:
          name: Cache npm dependencies
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - ~/nextjs-typescript-firebase/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - save_npm

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Lint
          command: npm run lint
      - save_npm

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Build
          command: npm run build
      - save_npm

  test:
    executor:
      name: default
    steps:
      - checkout
      - restore_npm
      - run:
          name: Test
          command: npm run test
      - save_npm

workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - test:
          requires:
            - build
